Traceback (most recent call last):
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jordanbarker/miniconda3/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def print_adf_results(adf_test):
    test_statistic, p_value, used_lag, nobs, critical_values, icbest = adf_test
    print(f"Test Statistic: {test_statistic:.4f}")
    print(f"P-Value: {p_value:.4f}")
    print(f"Number of Lags Used: {used_lag}")
    # print(f"Number of Observations: {nobs}")
    print("Critical Values:")
    for key, value in critical_values.items():
        print(f"    {key}: {value:.4f}")
    print(f"Maximized Information Criterion: {icbest:.4f}")
    
    

print_adf_results(stationarity_test_adf(train[['total']], maxlag=365))
print('\nWith differencing:')
print_adf_results(stationarity_test_adf(train[['total']].diff(), maxlag=365))
print('\nWith log-transform and differencing:')
print_adf_results(stationarity_test_adf(train[['total']].map(np.log).diff(), maxlag=365))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 14[0m
[1;32m      9[0m         [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m    [39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00mvalue[38;5;132;01m:[39;00m[38;5;124m.4f[39m[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     10[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mMaximized Information Criterion: [39m[38;5;132;01m{[39;00micbest[38;5;132;01m:[39;00m[38;5;124m.4f[39m[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m---> 14[0m print_adf_results([43mstationarity_test_adf[49m(train[[[38;5;124m'[39m[38;5;124mtotal[39m[38;5;124m'[39m]], maxlag[38;5;241m=[39m[38;5;241m365[39m))
[1;32m     15[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124mWith differencing:[39m[38;5;124m'[39m)
[1;32m     16[0m print_adf_results(stationarity_test_adf(train[[[38;5;124m'[39m[38;5;124mtotal[39m[38;5;124m'[39m]][38;5;241m.[39mdiff(), maxlag[38;5;241m=[39m[38;5;241m365[39m))

[0;31mNameError[0m: name 'stationarity_test_adf' is not defined

